services:
  go.ecommerce.com:
    environment:
        - APP_ENV=prod
    container_name: go_ecommerce
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on: 
      - mysql
      - redis
    ports:
      - "8002:8082"

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: root1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes: 
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: 