// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"go-ecommerce/internal/controller/user"
	user2 "go-ecommerce/internal/service/user"
)

// Injectors from user.wire.go:

func InitLoginRouterHandler() (*user.LoginController, error) {
	iUserLogin := user2.UserLoginService()
	loginController := user.NewLoginController(iUserLogin)
	return loginController, nil
}

func InitRegisterRouterHandler() (*user.RegisterController, error) {
	iUserRegister := user2.UserRegisterService()
	registerController := user.NewRegisterController(iUserRegister)
	return registerController, nil
}
