server:
  port: 8082
  mode: dev
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: root1234
  dbName: db
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
log:
  log_level: debug
  file_log_name: "./storage/logs/dev.log"
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true
redis:
  host: 127.0.0.1
  port: 6379
  password:
  database: 0
smtp:
  host: smtp.gmail.com
  username: linhvu2695@gmail.com
  password: ehhhextvsaqvfhfr
jwt:
  token_hour_lifespan: 1
  jwt_expiration: "1h"
  api_secret: "xxx.yyy.zzz"
